Ajax, Services/ViewModels/Layout/LayoutVM.cs
namespace Practice.ViewModels.Layout
{
    public class LayoutVM
    {
        public Dictionary<string,string> Settings { get; set; }
        public int  BasketCount { get; set; }

        //public decimal GrandTotal { get; set; }
    }
}

Ajax, Services/Controllers/ShopController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Practice.Data;
using Practice.Models;
using Practice.Services.Interfaces;
using Practice.ViewModels.Basket;

namespace Practice.Controllers
{
    public class ShopController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IBasketService _basketService;
        public ShopController(AppDbContext context, IBasketService basketService)
        {
            _context = context;
            _basketService = basketService;
        }

        public async Task<IActionResult> Index()
        {
            int count = await _context.Products
                .Where(p=>!p.SoftDelete)
                .CountAsync();
            ViewBag.Count = count;

            IEnumerable<Product> products = await _context.Products
                .Include(p=>p.Images)
                .Include(p=>p.Category)
                .Where(p=>!p.SoftDelete)
                .Take(4)
                .ToListAsync();

            IEnumerable<Category> categories = await _context.Categories
                .Where(p => !p.SoftDelete)
                .ToListAsync();

            ViewBag.Categories = categories;

            return View(products);
        }
        public async Task<IActionResult> LoadMore(int skip)
        {
            IEnumerable<Product> products = await _context.Products
              .Include(p => p.Images)
              .Where(p => !p.SoftDelete)
              .Skip(skip)
              .Take(4)
              .ToListAsync();

            return PartialView("_ProductsPartial", products);
        }

        [HttpPost]
        public async Task<IActionResult> AddBasket(int? id)
        {
            if (id is null) return BadRequest();

            Product dbProduct = await GetProductById((int)id);

            if (dbProduct == null) return NotFound();

            List<BasketVM> baskets = _basketService.GetDatasFromCookie();

            BasketVM existProduct = baskets.FirstOrDefault(p => p.Id == id);

            var basketCount = baskets.Count();

            _basketService.SetDatasToCookie(baskets, existProduct, dbProduct);

            return Ok(basketCount);
        }
        public async Task<Product> GetProductById(int id)
        {
            return await _context.Products.FindAsync(id);
        }
      
        public async Task<IActionResult> Search(string searchText)
        {
            if (String.IsNullOrWhiteSpace(searchText))
            {
                return Ok();
            }
            var products = await _context.Products
                .Include(p => p.Images)
                .Include(p => p.Category)
                .OrderByDescending(p=>p.Id)
                .Where(p => p.Name.ToLower().Contains(searchText.ToLower()) 
                               || p.Category.Name.ToLower().Contains(searchText.ToLower()))
                .ToListAsync();

            return PartialView("_SearchPartial",products);
        }
    }
}

Ajax, Services/Views/Shared/_ProductsPartial.cshtml
@model IEnumerable<Product>

@foreach (var product in Model)
{
    <div class="col-sm-6 col-md-4 col-lg-3 mt-3" >
        <div class="product-item product-item-small text-center " >
            <div class="img">
                <a href="">
                    <img src="~/img/@product.Images.FirstOrDefault()?.Image" class="img-fluid" alt="">
                </a>
            </div>
            <div class="overlay d-flex flex-column justify-content-center">
                <div class="title mt-3">
                    <h6>@product.Name</h6>
                </div>
                <div class="price">
                    <span class="text-black-50">$@product.Price</span>
                </div>
                <div class="button mt-3">
                    <form method="post" data-id="@product.Id">
                      <button class="btn btn-danger rounded-0">Add to cart</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
}

Ajax, Services/Views/Shared/_SearchPartial.cshtml
@model List<Product>

@foreach (var item in Model)
{
    <li class="d-flex px-3">
        <span class="mr-2">@item.Category.Name</span>
        <a asp-controller="Shop" asp-action="detail" asp-route-id="@item.Id">@item.Name</a>
    </li>
}

Ajax, Services/Views/Shared/_ShopCartPartial.cshtml
@model List<BasketVM>

<div class="cart-total">
    <span class="text-number">
        @Model.Count
    </span>
    <span class="text-item">
        Shopping Cart
    </span>
    <span class="price">
        @{
            double total = 0;

            //foreach (BasketVM basketVM in Model)
            //{
            //    total += (basketVM.Count * basketVM.Price);
            //}
        }

        £@total.ToString("F2")
        <i class="fas fa-chevron-down"></i>
    </span>
</div>
@*<div class="cart-dropdown-block">
    @foreach (BasketVM basketVM in Model)
    {
        <div class=" single-cart-block ">
            <div class="cart-product">
                <a href="~/product-details.html" class="image">
                    <img src="~/image/products/@basketVM.MainImage" alt="">
                </a>
                <div class="content">
                    <h3 class="title">
                        <a href="~/product-details.html">
                            @basketVM.GenreName @basketVM.Title
                        </a>
                    </h3>
                    <p class="price"><span class="qty">@basketVM.Count ×</span> £@basketVM.Price.ToString("F2")</p>
                    <button class="cross-btn"><i class="fas fa-times"></i></button>
                </div>
            </div>
        </div>
    }
    <div class="single-cart-block ">
        <div class="btn-block">
            <a asp-controller="Basket" asp-action="Index" class="btn">
                View Cart <i class="fas fa-chevron-right"></i>
            </a>
            <a href="~/checkout.html" class="btn btn--primary">
                Check Out <i class="fas fa-chevron-right"></i>
            </a>
        </div>
    </div>
</div>*@